/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.solteq.liferay.training.employees.repository.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the STQEmployee service. Represents a row in the &quot;stq_STQEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.solteq.liferay.training.employees.repository.db.model.impl.STQEmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.solteq.liferay.training.employees.repository.db.model.impl.STQEmployeeImpl</code>.
 * </p>
 *
 * @author Solteq
 * @see STQEmployee
 * @generated
 */
@ProviderType
public interface STQEmployeeModel extends BaseModel<STQEmployee>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a stq employee model instance should use the {@link STQEmployee} interface instead.
	 */

	/**
	 * Returns the primary key of this stq employee.
	 *
	 * @return the primary key of this stq employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this stq employee.
	 *
	 * @param primaryKey the primary key of this stq employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee ID of this stq employee.
	 *
	 * @return the employee ID of this stq employee
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this stq employee.
	 *
	 * @param employeeId the employee ID of this stq employee
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the company ID of this stq employee.
	 *
	 * @return the company ID of this stq employee
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this stq employee.
	 *
	 * @param companyId the company ID of this stq employee
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the first name of this stq employee.
	 *
	 * @return the first name of this stq employee
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this stq employee.
	 *
	 * @param firstName the first name of this stq employee
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this stq employee.
	 *
	 * @return the last name of this stq employee
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this stq employee.
	 *
	 * @param lastName the last name of this stq employee
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email of this stq employee.
	 *
	 * @return the email of this stq employee
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this stq employee.
	 *
	 * @param email the email of this stq employee
	 */
	public void setEmail(String email);

	/**
	 * Returns the job title of this stq employee.
	 *
	 * @return the job title of this stq employee
	 */
	@AutoEscape
	public String getJobTitle();

	/**
	 * Sets the job title of this stq employee.
	 *
	 * @param jobTitle the job title of this stq employee
	 */
	public void setJobTitle(String jobTitle);

	/**
	 * Returns the phone number of this stq employee.
	 *
	 * @return the phone number of this stq employee
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this stq employee.
	 *
	 * @param phoneNumber the phone number of this stq employee
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the company name of this stq employee.
	 *
	 * @return the company name of this stq employee
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this stq employee.
	 *
	 * @param companyName the company name of this stq employee
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the department of this stq employee.
	 *
	 * @return the department of this stq employee
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this stq employee.
	 *
	 * @param department the department of this stq employee
	 */
	public void setDepartment(String department);

	/**
	 * Returns the work location of this stq employee.
	 *
	 * @return the work location of this stq employee
	 */
	@AutoEscape
	public String getWorkLocation();

	/**
	 * Sets the work location of this stq employee.
	 *
	 * @param workLocation the work location of this stq employee
	 */
	public void setWorkLocation(String workLocation);

	@Override
	public STQEmployee cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}