/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.solteq.liferay.training.employees.repository.db.model.impl;

import com.solteq.liferay.training.employees.repository.db.model.STQEmployee;
import com.solteq.liferay.training.employees.repository.db.service.STQEmployeeLocalServiceUtil;

/**
 * The extended model base implementation for the STQEmployee service. Represents a row in the &quot;stq_STQEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link STQEmployeeImpl}.
 * </p>
 *
 * @author Solteq
 * @see STQEmployeeImpl
 * @see STQEmployee
 * @generated
 */
public abstract class STQEmployeeBaseImpl
	extends STQEmployeeModelImpl implements STQEmployee {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a stq employee model instance should use the <code>STQEmployee</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			STQEmployeeLocalServiceUtil.addSTQEmployee(this);
		}
		else {
			STQEmployeeLocalServiceUtil.updateSTQEmployee(this);
		}
	}

}