version: "3.4"
services:
  database:
    container_name: $COMPOSE_PROJECT_NAME-database
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_DB=lportal
      - POSTGRES_USER=lportal
      - POSTGRES_PASSWORD=lportal
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: liferay-training-db-data
        target: /var/lib/postgresql/data
volumes:
  liferay-training-db-data: